### ISSUE TITLE
很赞的组件

### ISSUE THREAD

**Issue by pronebel** [jingjingke/crontab#2]
你好~~ 

做后台的时候找到你的组件很赞.为了方便在后台用,我fork了变成组件lib的方式输出
https://github.com/pronebel/crontab
需要的话,可以合并过去 ^_^

建议这个组件可以 发布到npm去,这样会蛮多人用的,虽然这个组件是低频使用.

**Comment by jingjingke** [comment]
好的，谢谢你的，这个我还不太会弄，研究一下~刚才有修复一个bug："src/components/crontab-result.js"有新增几行代码。
